name: ycb-006_mustard_bottle-20200709-subject-01-20200709_143211

shape_meta: &shape_meta
  # acceptable types: rgb, low_dim
  obs:
    point_cloud:
      shape: [2048, 3]
      type: point_cloud
    agent_pos:
      shape: [22]
      type: low_dim
  action:
    shape: [22]

env_runner:
  _target_: algos.imitate.env_runner.sapien_runner.SapienRunner
  n_train: 100
  max_steps: 60
  n_obs_steps: ${n_obs_steps}
  n_action_steps: ${n_action_steps}
  fps: 20
  task_name: ${test_task_name}
  real_robot: False
  noisy_points: ${noisy_points}
  point_cs: ${point_cs}

dataset:
  _target_: dataset.trajectory_dataset.TrajectoryDataset
  zarr_path: data/${task_name}.zarr
  horizon: ${horizon}
  pad_before: ${eval:'${n_obs_steps}-1'}
  pad_after: ${eval:'${n_action_steps}-1'}
  seed: 42
  val_ratio: 0.00
  max_train_episodes: null
  noisy_points: ${noisy_points}
  noisy_states: ${noisy_states}
  point_cs: ${point_cs}
